### ISSUE TITLE
Bug - Increase in Innodb_history_list_length

### ISSUE THREAD

**Issue by davinc71998** [julien-duponchelle/python-mysql-replication#430]
## Problem
MySQL 8.0+: The value of Innodb_history_list_length steadily increases after running the program
The increase in Innodb_history_list_length is expected to have the following effects on MySQL
* Increased response time to user query

## Bug description
https://github.com/julien-duponchelle/python-mysql-replication/blob/62a009cd81b3a0c4928933cf4d8657376bfee5b1/pymysqlreplication/binlogstream.py#L638-L655
According to the logic written in binlogstream.py
After executing a query through the cursor, the transaction remains in place until the program exits

![스크린샷 2023-08-22 오후 11 06 03](https://github.com/julien-duponchelle/python-mysql-replication/assets/65767734/285f226d-eeba-416d-85f5-473811972f03)

the transaction is being maintained, the Innodb_history_list_length value will continue to increase when DML is performed.
![KakaoTalk_Photo_2023-08-22-23-18-38](https://github.com/julien-duponchelle/python-mysql-replication/assets/65767734/d24cb198-54e5-4298-9369-0d9e33c92aa6)

## Solution
After executing the query, ``COMMIT``  the transaction so that it can be terminated normally.

**Comment by dongwook-chan** [comment]
I'm glad that this issue was created and hope this issue is immediately attended. I work at Kakao which operates the most prominent messaging service in South Korea. My team integrated the python-mysql-replication for a range of applications. However, given the substantial DML traffic we handle (we have about 48m monthly active users), we observed a surge in `Innodb_history_list_length`, leading to challenges like delayed query responses and heightened server load.
